### PR TITLE
Update github.js

### PR DESCRIPTION
**Pull request by krsntn**
more closer match to github theme

### CODE REVIEW

**Comment by kitten** [comment]
Hiya 👋 this is some amazing work! Do you have a short description or summary of how you arrived on some of the changes, even if some of it may just come down to matching some discrepancies manually?

**Comment by krsntn** [comment]
I working on my project which came across to use this github theme. Somehow I find it not really matching with the current github theme. Therefore, to fulfill the need in my project, I updated this github theme accordingly.

**Comment by zepatrik** [comment]
It would have been nice to not remove all kinds of general token (e.g. string, symbol, namespace) classes, but instead update their styles. This completely broke some of my custom language definitions after updating...

**Comment by lex111** [comment]
Note that this change causes serious regression, for example, just compare syntax highlighting for HTML:

Due to the high color contrast, the code is difficult to read.

| Before   | After    |
| -------- | -------- |
| image | image |

Moreover, this doesn't match GitHub's color scheme, since it should be as on screenshot below:

image

Apparently not only I faced such problem, other people are also forced to rollback "prism-react-renderer" to the previous "stable" version (1.1.1)

https://github.com/seek-oss/scoobie/commit/f58f3f01e22ccb49988ebc8297084f135be3e493

**Comment by kitten** [comment]
I've reverted PR #100 that changed the styles for now until I can check which changes from it are save to pick over: https://github.com/FormidableLabs/prism-react-renderer/commit/0040cd472d20cb8863a1740ee88fd276e8497601

**Comment by zepatrik** [comment]
In fact, @krsntn probably used dark mode when doing this. Maybe move this to a separate theme instead? Maybe he can clarify how he came up with this?

**Pull request merged**
