### PR TITLE
Add Okaidia theme

### PR DESCRIPTION
**Pull request by yakkomajuri**
Ported over from:

https://github.com/PrismJS/prism/blob/1761513e3db48ca9222037644a9c68746e24f039/themes/prism-okaidia.css

Happy to get @ocodia's blessing here.

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Not sure who to tag here - @JonShort ?

**Comment by JonShort** [comment]
👋 I think Phil is the maintainer of this library (I just had something merged last 😆)

Either way, I shimmed your work [into a sandbox](https://codesandbox.io/s/prism-react-renderer-okaidia-jnrwx) and it looks good 👍 I'm not really familar with the theme, but looking at [official okaidia example](https://prismjs.com/#examples) it looks like there might be some differences, mostly in the non-JS syntax highlighting

(Again, I'm not familar with the theme so might be missing something 😁 - if so, feel free to ignore this)

---
image

---
Link to sandbox - https://codesandbox.io/s/prism-react-renderer-okaidia-jnrwx
Link to official example - https://prismjs.com/#examples (ensure 'okaidia' is selected on right column radio buttons)

**Comment by yakkomajuri** [comment]
By no means! Thanks for the feedback - I put this together quickly for a personal need, but tagged the original theme author to get feedback. Will update accordingly!

**Comment by yakkomajuri** [comment]
Some significant updates here, but I don't believe this can be perfect because it seems the two libraries have some differences when parsing the languages and adding the class names to the code. 

HTML tags for example are rendered as `plain` in the sandbox, and `tag` in the official Prism website.

**Comment by yakkomajuri** [comment]
Could be wrong though - have been quite busy so not too much time to look into everything

**Pull request merged**
