### PR TITLE
Fix token aliases and upgrade Prism

### LINKED ISSUE #14: Aliases representing classes is not applied.
It seems there is an issue with aliases. 
For example here is a rule:
```Prism.languages.insertBefore('php', 'keyword', {
    'delimiter': {
      pattern: /\?>|<\?(?:php|=)?/i,
      alias: 'important'
    },
    'variable': /\$+(?:\w+\b|(?={))/i,
    'package': {
      pattern: /(\\|namespace\s+|use\s+)[\w\\]+/,
      lookbehind: true,
      inside: {
        punctuation: /\\/
      }
    }
  });
```

The alias `important` is not applied. It means there is no class `important` for the `<?php` element. 
However, in the official test it works:
screen-01-16-13
And it's relevant for all other aliases.

### LINKED ISSUE #29: Improve tokenization
As mentioned in https://github.com/FormidableLabs/prism-react-renderer/pull/28#issuecomment-469053981, the tokenization and classes leave some things to be desired.

Would it fit the goals of this project to improve the support of the tokenization? I'm looking at this in terms of implementing more fully-featured themes, such as what I started in #28.

An example is this:

**prism-react-renderer with Improved VS Code theme (#28)**

screen shot 2019-03-04 at 17 58 24
screen shot 2019-03-04 at 17 58 36

**VS Code**
screen shot 2019-03-04 at 18 14 10

Would be nice to get a bit closer to VS Code's version (`<`, `=` and `"` punctuation highlighted differently).

---

Looking more in detail, I see that there are some limitations inherent in Prism, but maybe there could still be some improvements somehow, such as integration of Prism JS Extras: https://github.com/PrismJS/prism/pull/1743

---

If improving tokenization is not easy or possible without changing Prism, one thing that could be easier to do would be to allow for changing the `plain` colors by language, so that the CSS `plain` could be the orange color instead of the light blue (which is more common throughout, which is why I opted to use it).

**prism-react-renderer with Improved VS Code theme (#28)**

css-after

**VS Code**

css-real-vs-code

### PR DESCRIPTION
**Pull request by kitten**
Fix #29 
Fix #14 

This adds support for token aliases, which was unfortunately missing before. It also upgrades `prismjs` and ensures that `js-extras` is included.

@karlhorky Sorry, this might be as good as we can get it for now without some tremendous extra-effort. Testing these changes would be appreciated, if you have the time 🙌

### CODE REVIEW

**Comment by kitten** [comment]
@karlhorky it's basically sth that is already present in Prism themes but that I forgot to add support for. In certain cases themes can specify "aliases" which are more specific types of tokens that should take precedence over the other types. One example afaik are keywords being marked as "important" in JS

**Comment by karlhorky** [comment]
Ah cool, yeah then I suppose that may enable things like what I was trying to accomplish with styling the `=` and `"`, cool!

https://github.com/FormidableLabs/prism-react-renderer/issues/29#issue-416908053

**Comment by karlhorky** [comment]
Oh I've guess it won't for this exact case (see my request to improve the Prism.js tokenization: PrismJS/prism#1871) but it will maybe improve other cases.

**Comment by kitten** [comment]
Yeah, I don't see any regressions from this PR, so I'll ship it, and if Prism improves some syntaxes we'll definitely profit from it 😅

**Comment by karlhorky** [comment]
Awesome, thanks! Is there going to be a new version published too?

**Pull request merged**
