### PR TITLE
Add rust and html to includedLangs

### LINKED ISSUE #166: Type '"html"' is not assignable to type 'Language'
Why it's not accepting 'html'? But it seems to be working.

Screen Shot 2022-09-09 at 22 53 10

### LINKED ISSUE #171: Add Rust language support
I am writing to request that Rust language support be added to this repository. Rust is a fast and safe language that is well-suited for projects that require performance and reliability, and its popularity has been rising considerably. I believe that adding Rust language support would benefit the community of users and contributors to this repository.

Please let me know if you have any questions or concerns about adding Rust language support. I look forward to your response. Thank you for considering my request.

### PR DESCRIPTION
**Pull request by rilakumma**
closes #171
closes #166

### CODE REVIEW

**Review by gksander — APPROVED** [review]
Looks good to me. Did you find any good way to test out these changes? (Doesn't look like we have much of a test-suite, so I'm not sure if there's a specific/easy way to test these things out, other than just installing it in a react app and trying them?)

**Comment by stellenberger** [comment]
Is there any chance we can include Ruby as well?

**Comment by rilakumma** [comment]
>

**Comment by rilakumma** [comment]
> 

yeah i did test it out on the demo app with this branch and was able to see rust and html styling,
Screen Shot 2023-02-17 at 2 44 38 PM
also, i think that for html we already had that set up as `markup` so we dont need to add the `html` alias

**Pull request closed without merging**
