### PR TITLE
Add java as a language type

### PR DESCRIPTION
**Pull request by bmorrise**
I'm wanting to use this in a Java source project and figured java would make a good addition to the languages.

### CODE REVIEW

**Comment by mdamour1976** [comment]
Yes please :)

**Comment by ccaspanello** [comment]
I'm kind of surprised this is not enabled by default.  We too are looking to use Java

**Comment by kitten** [comment]
Hiya 👋
This may change in a future version of I revisit prism-react-renderer entirely, but right now the idea is that it only includes a limited set instead of all languages. That means we don't have plans here to change this much and include more and more languages that Prism support. Because eventually that'd mean we'd just enable all.

There's an entry in the FAQ though on how to enable more languages via the Prism package.

**Comment by bmorrise** [comment]
The issue I'm seeing is that since "java" doesn't exist as a valid type for Language in TypeScript I get an error on compile. I have manually edited the index.d.ts file as a workaround. Is there a way to avoid this compilation error without a code update?

**Comment by kitten** [comment]
You could retype the component to make this work. Ultimately since custom languages can also be added to Prism it's not feasilble to keep adding more language types. So either it'll have to be retyped as `string` or on your end you'll have to recast it; either by changing the component type or by passing in a forced cast to the literal

**Pull request closed without merging**
